import type { Challenge } from './index';

// Challenge rooms and mastery trials: short, self-contained puzzles with a
// twist. They unlock with mastery marks earned in the campaign.

const W = '##############################';

export const CHALLENGE_DEFS: Challenge[] = [
  {
    kind: 'room',
    unlockMarks: 8,
    rule: 'Only one echo.',
    def: {
      id: 'c-1',
      name: 'Lone Witness',
      world: 0,
      objective: 'Open both doors with a single echo.',
      loopSeconds: 20,
      maxEchoes: 1,
      parEchoes: 1,
      parTime: 3.5,
      map: [
        W,
        W,
        W,
        W,
        W,
        W,
        W,
        W,
        '#........#####################',
        '#........#####################',
        '#........#####################',
        '#........#####################',
        '#............................#',
        '#............................#',
        '#.....P......................#',
        W,
        W,
      ],
      objects: [
        { type: 'plate', id: 'p', x: 2, y: 14 },
        { type: 'switch', id: 's', x: 4, y: 11, timer: 1.5 },
        { type: 'door', x: 9, y: 12, w: 1, h: 3, open: 'p' },
        { type: 'door', x: 24, y: 12, w: 1, h: 3, open: 's' },
        { type: 'exit', x: 27, y: 14 },
      ],
      hints: [
        'The plate holds the first door; the switch opens the far one only briefly.',
        'One echo can do two jobs, one after the other.',
        'Let your echo stand on the plate until you are through, then flip the switch as you reach the far door.',
        'Take 1: sit on the plate for about a second, then jump into the switch. Take 2: run straight for the exit.',
      ],
      solution: ['go 2; w 50; go 4; j 24; land; w 30; end', 'go 27'],
    },
  },
  {
    kind: 'room',
    unlockMarks: 16,
    rule: 'The loop lasts only 6 seconds.',
    def: {
      id: 'c-2',
      name: 'Six Seconds',
      world: 0,
      objective: 'Climb to the exit before the loop runs out.',
      loopSeconds: 6,
      maxEchoes: 2,
      parEchoes: 2,
      parTime: 5.2,
      map: [
        W,
        W,
        W,
        W,
        W,
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#.......................######',
        '#.......................######',
        '#.......................######',
        '#.......................######',
        '#.......................######',
        '#..P....................######',
        W,
        W,
      ],
      objects: [
        { type: 'plate', id: 'a', x: 1, y: 14 },
        { type: 'door', x: 26, y: 5, w: 1, h: 4, open: 'a' },
        { type: 'exit', x: 28, y: 8 },
      ],
      hints: [
        'The ledge is too high to jump, and the door on it needs the plate.',
        'Six seconds is not enough for one echo to do both jobs.',
        'Give each job its own echo, and start them right away.',
        'Take 1: sit on the plate. Take 2: run to the foot of the ledge and wait. Take 3: ghost-bounce up and go through the door.',
      ],
      solution: ['go 1; w 6s', 'go 23; w 6s', 'go 21.5; j 20; land 23; jr 30; go 28'],
    },
  },
  {
    kind: 'room',
    unlockMarks: 26,
    rule: 'Low gravity: every landing is soft.',
    def: {
      id: 'c-3',
      name: 'Featherfall',
      world: 0,
      objective: 'Smash into the vault. Its exit only shines while the plate is held.',
      loopSeconds: 20,
      maxEchoes: 2,
      parEchoes: 1,
      parTime: 7,
      tuning: { gravity: 800, fastFallGravity: 800 },
      map: [
        W,
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#..P.........................#',
        '#######################...####',
        '#######################......#',
        '#######################......#',
        W,
        W,
      ],
      objects: [
        { type: 'plate', id: 'a', x: 10, y: 11 },
        { type: 'breakable', x: 23, y: 12, w: 3, h: 1, strength: 650 },
        { type: 'exit', x: 27, y: 14, active: 'a' },
      ],
      hints: [
        'The cracked lid will not give under a normal jump — everything falls too gently here.',
        'Fall from much higher and the lid breaks. Echoes throw you higher than any jump.',
        'Two echoes make it easy. One echo can do both jobs: be your springboard first, then walk to the plate while you float.',
        'Take 1: wait beside the lid until you have bounced off, then go sit on the plate. Take 2: ghost-bounce off your echo, drift onto the lid and smash through.',
      ],
      solution: ['go 22; until 215; go 10; w 15s', 'go 20.5; j 10; land 22; jr 30; go 24; land; go 27; w 2s'],
    },
  },
  {
    kind: 'room',
    unlockMarks: 38,
    rule: 'The whole floor is ice.',
    def: {
      id: 'c-4',
      name: 'Glass Hall',
      world: 0,
      objective: 'Reach the exit above the spikes.',
      loopSeconds: 20,
      maxEchoes: 2,
      parEchoes: 2,
      parTime: 6,
      map: [
        W,
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#...........#................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#..P...................^^^^^^#',
        '#~~~~~~~~~~~~~~~~~~~~~~~~~~~~#',
        W,
      ],
      objects: [
        { type: 'plate', id: 'a', x: 1, y: 14 },
        { type: 'door', x: 12, y: 10, w: 1, h: 5, open: 'a' },
        { type: 'exit', x: 24, y: 8 },
      ],
      hints: [
        'Nothing stops on ice by itself — only walls and patience.',
        'A wall is the easiest brake. Your echo can lean on one.',
        'You need a springboard right at the edge of the spikes. Brake early: ice slides a long way.',
        'Take 1: slide left onto the plate against the wall. Take 2: pass the door and brake to a stop at the edge of the spikes. Take 3: jump onto that echo and bounce up to the exit.',
      ],
      solution: ['l 60; w 18s', 'until 40; r 160; l 70; w 16s', 'until 70; r 147; jr 16; land 21.3; jr 30; r 60'],
    },
  },
  {
    kind: 'room',
    unlockMarks: 52,
    rule: 'The exit shines only while all three plates are held — with two echoes.',
    def: {
      id: 'c-5',
      name: 'Third Weight',
      world: 0,
      objective: 'Hold all three plates at once and reach the exit.',
      loopSeconds: 20,
      maxEchoes: 2,
      parEchoes: 2,
      parTime: 3.2,
      map: [
        W,
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '######.......................#',
        '######.......................#',
        '######.......................#',
        '######.......................#',
        '######.......P...............#',
        W,
        W,
      ],
      objects: [
        { type: 'plate', id: 'a', x: 6, y: 14 },
        { type: 'plate', id: 'b', x: 2, y: 9 },
        { type: 'plate', id: 'c', x: 25, y: 14 },
        { type: 'exit', x: 25, y: 13, active: 'a & b & c' },
      ],
      hints: [
        'Three plates, two echoes. Count again: who else has weight?',
        'You are the third weight. A plate stays pressed for a blink after you leave it.',
        'The high plate needs a springboard — and the springboard can stand on a plate of its own.',
        'Take 1: sit on the plate at the foot of the ledge. Take 2: ghost-bounce off it onto the ledge plate. Take 3: roll onto the far plate and hop into the exit.',
      ],
      solution: ['go 6; w 18s', 'go 8.5; j 20; land 6; jl 30; go 2; w 16s', 'go 25; until 150; j 10; w 30'],
    },
  },
  {
    kind: 'trial',
    unlockMarks: 66,
    rule: 'The far gate needs the plate and the switch at the same moment.',
    def: {
      id: 'c-6',
      name: 'Wound Spring',
      world: 0,
      objective: 'Open both gates and dash through the cracked wall.',
      loopSeconds: 20,
      maxEchoes: 2,
      parEchoes: 2,
      parTime: 9,
      abilities: ['burst'],
      map: [
        W,
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#.===####################==###',
        '#.############################',
        '#.#..........................#',
        '#.#..........................#',
        '#.#..........................#',
        '#.....P......................#',
        '#.############################',
        W,
      ],
      objects: [
        { type: 'spring', x: 1, y: 15, power: 950 },
        { type: 'plate', id: 'a', x: 25, y: 8, w: 2 },
        { type: 'switch', id: 's', x: 3, y: 3, timer: 1 },
        { type: 'door', x: 10, y: 11, w: 1, h: 4, open: 'a' },
        { type: 'breakable', x: 17, y: 11, w: 1, h: 4 },
        { type: 'door', x: 23, y: 11, w: 1, h: 4, open: 'a & s' },
        { type: 'shard', x: 27, y: 1 },
        { type: 'exit', x: 27, y: 14 },
      ],
      hints: [
        'The spring only goes up. Whoever rides it stays in the loft for good.',
        'The far gate wants the plate and the switch together, and the switch lets go quickly.',
        'One echo squashes on the rubber plate for the whole loop. The other waits by the switch and rubber-jumps into it once you stand at the far gate.',
        'Take 1: spring up, roll to the far rubber plate and hold Down. Take 2: spring up and bounce into the switch a few seconds in. Take 3: dash through the cracked wall and slip through the far gate while it is open.',
      ],
      solution: [
        'go 1; w 40; go 25.5; sq 19s',
        'go 1; w 40; go 6; until 350; go 3; j 24; w 60',
        'w 30; go 15; b r; r 20; go 22; land; go 27',
      ],
      lore: 'The Archivist wound the Horologe by hand each night. Tonight, it seems, the key is me — several of me.',
    },
  },
  {
    kind: 'trial',
    unlockMarks: 82,
    rule: 'Two echoes must turn to stone.',
    def: {
      id: 'c-7',
      name: 'Stone Witnesses',
      world: 0,
      objective: 'Reach the ledge beneath the beam and open the last door.',
      loopSeconds: 20,
      maxEchoes: 3,
      parEchoes: 3,
      parTime: 7.5,
      map: [
        W,
        '#............................#',
        '#............................#',
        '#............................#',
        '#....................#########',
        '#............................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#....................#########',
        '#....................#########',
        '#....................#########',
        '#....................#########',
        '#...........#.........########',
        '#..P.................#########',
        '########.#####################',
        W,
      ],
      objects: [
        { type: 'laser', x: 8, y: 15, dir: 'up' },
        { type: 'plate', id: 'p', x: 8, y: 14 },
        { type: 'laser', x: 21, y: 13, dir: 'left' },
        { type: 'door', x: 24, y: 5, w: 1, h: 4, open: 'p' },
        { type: 'exit', x: 27, y: 8 },
      ],
      hints: [
        'The plate lies in a beam, and a second beam hangs just above your head.',
        'Anything that touches a beam turns to stone — and stone stays for the whole loop, pressing plates and blocking light.',
        'One echo must become stone on the plate. Another must jump into the low beam right at its emitter to shade the whole hall. A third, alive, is your springboard.',
        'Take 1: roll into the light on the plate. Take 2: jump into the low beam next to the ledge. Take 3: wait two tiles left of the ledge. Take 4: bounce off that echo onto the ledge and through the door.',
      ],
      solution: ['go 9', 'w 30; go 6.3; jr 14; land 10; go 20; j 10', 'w 60; go 6.3; jr 14; land 10; go 19; w 18s', 'w 90; go 6.3; jr 14; land 10; go 17.5; j 20; land 19; jr 30; go 27'],
    },
  },
  {
    kind: 'trial',
    unlockMarks: 100,
    rule: 'Nothing to stand on up there: build a ladder in the air.',
    def: {
      id: 'c-8',
      name: 'Many Selves',
      world: 0,
      objective: 'Climb the hall to the exit on a ladder of your own echoes.',
      loopSeconds: 20,
      maxEchoes: 3,
      parEchoes: 3,
      parTime: 5,
      abilities: ['anchor'],
      map: [
        W,
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#############................#',
        '#............................#',
        '#............................#',
        '#............................#',
        '#......P.....................#',
        '##############################',
        W,
      ],
      objects: [
        { type: 'plate', id: 'q', x: 1, y: 14, w: 2 },
        { type: 'door', x: 12, y: 11, w: 1, h: 4, open: 'q' },
        { type: 'shard', x: 22, y: 2 },
        { type: 'exit', x: 19, y: 3 },
      ],
      hints: [
        'The exit hangs far above the hall, and there is no ledge to climb.',
        'An anchored echo is a springy perch that hangs in the air for a moment — if you can land on top of it.',
        'One echo holds the plate. One waits just past the door as a springboard. One bounces off it and anchors on the way down, a little lower than your own bounce reaches.',
        'Take 1: hold the plate. Take 2: wait just past the door. Take 3: ghost-bounce off it to the right and anchor as you start to fall. Take 4: ghost-bounce off the waiting echo, land on the anchored one and bounce again to the exit.',
      ],
      solution: [
        'go 1.5; w 19s',
        'w 30; go 14; w 18s',
        'w 60; go 12.2; j 20; land 14; jr 30; until 192; a 150',
        'w 90; go 12.2; j 20; land 14; jr 30; land 19.25; j 30; go 19; w 30',
      ],
      lore: 'The Archivist split into many selves to hold the Horologe together. Now I know which one I am: the last, and the one who wakes it.',
    },
  },
];
