import type { LevelDef } from '../core/types';

// World 2 — Shared Weight. Elevators and ferries that move only while their
// plates are held, AND-logic that needs several echoes at once, echoes that
// ride platforms, and squashing (Down) to rest steadily on bouncy plates.

const W = '##############################';
const E = '#............................#';

export const WORLD2: LevelDef[] = [
  {
    id: 'w2-1',
    name: 'Lift',
    world: 2,
    objective: 'Ride the lift to the high ledge.',
    loopSeconds: 20,
    maxEchoes: 1,
    parEchoes: 1,
    parTime: 6.5,
    map: [
      W,
      E,
      E,
      E,
      E,
      '#............####............#',
      '#......................#######',
      '#......................#######',
      '#......................#######',
      '#......................#######',
      '#......................#######',
      '#......................#######',
      '#......................#######',
      '#......................#######',
      '#................P.....#######',
      '####################...#######',
      W,
    ],
    objects: [
      { type: 'plate', id: 'p', x: 3, y: 14, w: 2 },
      { type: 'platform', x: 20, y: 15, w: 3, to: [[20, 6]], speed: 3, active: 'p' },
      { type: 'sign', x: 10, y: 12, text: 'Lit platforms move while their plate is held' },
      { type: 'shard', x: 15, y: 4 },
      { type: 'exit', x: 26, y: 5 },
    ],
    hints: [
      'The platform in the floor is a lift. The plate far to the left drives it.',
      'The lift only rises while something weighs down the plate.',
      'Let your echo take the long walk to the plate while you wait on the lift.',
      'Take 1: walk to the plate and stay, press R. Take 2: stand on the lift, ride it up, roll right to the exit.',
    ],
    solution: ['go 3.5; w 15s; end', 'go 21; w 4s; go 26'],
    lore: 'The builders raised the Horologe one lift at a time. Someone always stayed below, holding the weight.',
  },
  {
    id: 'w2-2',
    name: 'Steady Hands',
    world: 2,
    objective: 'Raise the bridge and cross the chasm.',
    loopSeconds: 20,
    maxEchoes: 2,
    parEchoes: 2,
    parTime: 7.5,
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      E,
      '#......P.....................#',
      '##..######.............#######',
      '##==######.............#######',
      '##########.............#######',
      '##########.............#######',
      '##########.............#######',
      '##########.............#######',
      '##########.............#######',
      '##########.............#######',
      W,
    ],
    objects: [
      { type: 'plate', id: 'a', x: 5, y: 7 },
      { type: 'plate', id: 'b', x: 2, y: 8, w: 2 },
      { type: 'platform', x: 10, y: 15.5, w: 13, to: [[10, 8]], speed: 3, active: 'a & b' },
      { type: 'sign', x: 3, y: 5, text: 'Hold ↓ to squash — rest still on bouncy floors' },
      { type: 'sign', x: 16, y: 6, text: 'The bridge rises only while both plates are held' },
      { type: 'shard', x: 16, y: 4 },
      { type: 'exit', x: 26, y: 7 },
    ],
    hints: [
      'The bridge at the bottom of the chasm has two plates. It rises only while both are pressed.',
      'The plate in the rubber pit keeps bouncing you off — unless you squash.',
      'One echo on each plate. The one in the pit must hold ↓ the whole time.',
      'Take 1: sit on the stone plate. Take 2: drop into the pit and hold ↓. Take 3: wait for the bridge, then roll across.',
    ],
    solution: ['go 5; w 18s; end', 'go 2.5; sq 18s; end', 'w 3.6s; go 26'],
    lore: 'One of us alone could lift nothing. Two of us, and the stones began to move.',
  },
  {
    id: 'w2-3',
    name: 'Relay',
    world: 2,
    objective: 'Open the door without leaving the floor.',
    loopSeconds: 20,
    maxEchoes: 2,
    parEchoes: 2,
    parTime: 7.5,
    map: [
      W,
      '#....................#.......#',
      '#....................#.......#',
      '#....................#.......#',
      '#....................#.......#',
      '#....................#.......#',
      '#...........#####....#.......#',
      '#....................#.......#',
      '#....................#.......#',
      '#....................#.......#',
      E,
      E,
      E,
      E,
      '#.......P....................#',
      '#########...##################',
      W,
    ],
    objects: [
      { type: 'plate', id: 'p', x: 1, y: 14, w: 2 },
      { type: 'platform', x: 9, y: 15, w: 3, to: [[9, 6]], speed: 3, active: 'p' },
      { type: 'plate', id: 'q', x: 14, y: 5, w: 2 },
      { type: 'door', x: 21, y: 10, w: 1, h: 5, open: 'q' },
      { type: 'sign', x: 5, y: 11, text: 'Echoes ride lifts too' },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'The door listens to the plate on the high shelf, but you need to be down here.',
      'Echoes can ride lifts too.',
      'One echo drives the lift, a second one rides it up to the shelf plate.',
      'Take 1: sit on the far-left plate. Take 2: ride the lift up and sit on the shelf plate. Take 3: walk through the door.',
    ],
    solution: ['go 1.5; w 15s; end', 'go 10; w 4s; go 14.5; w 15s; end', 'go 19; until 320; go 26'],
  },
  {
    id: 'w2-4',
    name: 'Hold the Lift',
    world: 2,
    objective: 'Ride up, then get the high door open.',
    loopSeconds: 20,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 9.5,
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      '#...............##############',
      '#...............##############',
      '#...............##############',
      '#...............##############',
      '#...............##############',
      '#...............##############',
      '#...............##############',
      '#...............##############',
      '#..........P....##############',
      '#############...##############',
      W,
    ],
    objects: [
      { type: 'plate', id: 'a', x: 1, y: 14, w: 2 },
      { type: 'plate', id: 'c', x: 5, y: 14 },
      { type: 'plate', id: 'b', x: 9, y: 14 },
      { type: 'platform', x: 13, y: 15, w: 3, to: [[13, 6]], speed: 3, active: 'a & b' },
      { type: 'door', x: 20, y: 1, w: 1, h: 5, open: 'c' },
      { type: 'exit', x: 26, y: 5 },
    ],
    hints: [
      'The lift needs two plates; the door up top needs the third.',
      'Once you are off the lift, it no longer needs to stay up.',
      'An echo can hold the lift while you ride, then step across to the door plate.',
      'Take 1: sit on the far-left plate. Take 2: sit on the right plate for about 6 seconds, then move to the middle plate. Take 3: ride the lift and go through the door.',
    ],
    solution: ['go 1.5; w 18s; end', 'go 9; until 360; go 5; w 15s; end', 'go 14; w 4s; go 19; until 430; go 26'],
  },
  {
    id: 'w2-5',
    name: 'All Hands',
    world: 2,
    objective: 'Reach the top of the tower.',
    loopSeconds: 25,
    maxEchoes: 3,
    parEchoes: 3,
    parTime: 8.5,
    map: [
      W,
      E,
      E,
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#............#################',
      '#........P...#################',
      '#..#######...#################',
      '#==###########################',
    ],
    objects: [
      { type: 'plate', id: 'b', x: 1, y: 15, w: 2 },
      { type: 'plate', id: 'a', x: 4, y: 14, w: 2 },
      { type: 'platform', x: 10, y: 15, w: 3, to: [[10, 8]], speed: 3, active: 'a & b' },
      { type: 'shard', x: 7, y: 1 },
      { type: 'exit', x: 25, y: 2 },
    ],
    hints: [
      'Even at the top of the lift, the tower is out of reach.',
      'An echo standing on the lift is a springboard that rides along.',
      'Two echoes hold the plates, a third rides the lift and waits there.',
      'Take 1: squash in the rubber pit. Take 2: sit on the other plate. Take 3: ride the lift on its left side and stay. Take 4: ride on the right, then ghost-bounce off your echo onto the tower.',
    ],
    solution: [
      'go 1.5; sq 20s; end',
      'go 4.5; w 20s; end',
      'go 10.3; w 20s; end',
      'go 11.8; until 260; jl 12; land 10.3; jr 30; go 25',
    ],
    lore: 'We raised the last beam with every hand we had. Looking back, I think every hand was mine.',
  },
];
