import type { LevelDef } from '../core/types';

// World 6 — Fractured Timelines. The difference between past and present
// selves: pale veils that only stop echoes, plates and switches that answer
// to only one kind of self, and the anchor ability (echoes frozen in mid-air
// become springy perches for later selves).
//
// Note on veils and `who` filters: a take is always recorded by the live
// (player-kind) ball and replayed as a ghost. So an echo must never touch a
// ghost-blocking veil (it passed through it while being recorded), and an
// echo never counts on a player-only plate or switch, even though its
// recording did. Every level here is built around that asymmetry.

const W = '##############################';
const E = '#............................#';

export const WORLD6: LevelDef[] = [
  {
    id: 'w6-1',
    name: 'Pale Veil',
    world: 6,
    objective: 'Hold the plate beyond the veil and reach the exit.',
    loopSeconds: 25,
    maxEchoes: 2,
    parEchoes: 1,
    parTime: 7,
    abilities: ['burst'],
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      '#.......#.............#......#',
      '#.......#.............#......#',
      '#.......#.............#......#',
      '#...###.#.............#......#',
      '#.......#.............#......#',
      E,
      '###..........................#',
      '###..........................#',
      '###.P........................#',
      W,
      W,
    ],
    objects: [
      { type: 'veil', x: 8, y: 11, w: 1, h: 4, blocks: 'ghost' },
      { type: 'plate', id: 'p', x: 10, y: 14, w: 2 },
      { type: 'door', x: 22, y: 11, w: 1, h: 4, open: 'p' },
      { type: 'sign', x: 4, y: 7, text: 'Pale veils stop your echoes — not you' },
      { type: 'shard', x: 13, y: 2 },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'The shimmering gap in the wall lets you through, but your echoes bump into it.',
      'An echo only works if its path never touches a pale veil.',
      'Send your echo the long way: up the steps and over the wall, down onto the plate. You take the short way through the veil.',
      'Take 1: climb the steps, drop over the wall onto the plate and wait. Take 2: walk through the veil, hop over your echo and run to the exit.',
    ],
    solution: [
      'go 3; jl 20; land 1.5; go 1.5; jr 24; land 5; go 5; jr 24; land 8; go 8; r 20; land 10.5; go 10.5; w 5s; end',
      'until 150; go 8.5; jr 20; go 26',
    ],
    lore: 'The pale veils are scars. This is where I tore myself into many, so there would be enough hands to hold the Horologe together.',
  },
  {
    id: 'w6-2',
    name: 'Held Breath',
    world: 6,
    objective: 'Climb to the exit on the high ledge.',
    loopSeconds: 25,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 6,
    abilities: ['anchor'],
    map: [
      W,
      E,
      E,
      E,
      E,
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      '#.....P...............########',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 8, y: 9, text: 'Hold C / K: anchor — freeze in mid-air' },
      { type: 'sign', x: 8, y: 10, text: 'Anchored echoes are springy perches' },
      { type: 'exit', x: 26, y: 4 },
    ],
    hints: [
      'The ledge is far higher than a single ghost bounce.',
      'An anchored echo hangs in the air, and it is just as springy as one on the floor.',
      'Build a staircase out of your past: one echo waits on the floor, the next bounces off it and anchors in the air nearer the ledge.',
      'Take 1: wait near the ledge. Take 2: ghost bounce off it, drift right and anchor as you fall. Take 3: bounce off the floor echo, land on the anchored one and jump onto the ledge.',
    ],
    solution: [
      'go 16; w 200; end',
      'go 14; j 20; land 16; k JR 12; j 18; w 16; a 150; end',
      'go 14; until 150; j 20; land 16; k JR 12; j 18; land 20.8; k JR 30; go 26',
    ],
  },
  {
    id: 'w6-3',
    name: 'Unseen Hand',
    world: 6,
    objective: 'An echo must hold the pale plate; only you can flip the switch.',
    loopSeconds: 25,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 10.5,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '#......................#.....#',
      '#......................#.....#',
      '#............######....#.....#',
      '#......................#.....#',
      '#......................#.....#',
      '#......................#.....#',
      '#......................#.....#',
      '#......................#.....#',
      '#......................#.....#',
      '#......................#.....#',
      E,
      E,
      E,
      '#..P.........................#',
      W,
      W,
    ],
    objects: [
      { type: 'plate', id: 'g', x: 15, y: 2, w: 2, who: 'ghost' },
      { type: 'switch', id: 's', x: 9, y: 3, who: 'player' },
      { type: 'door', x: 23, y: 11, w: 1, h: 4, open: 'g & s' },
      { type: 'sign', x: 15, y: 9, text: 'Pale plates feel only echoes' },
      { type: 'sign', x: 15, y: 10, text: 'Dark switches answer only to you' },
      { type: 'shard', x: 4, y: 3 },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'The plate on the high shelf ignores you, and the switch beside it ignores your echoes.',
      'Only an echo can hold the plate and only you can flip the switch — but both are out of reach from the floor.',
      'One echo anchors in mid-air as a perch. A second echo uses it to reach the shelf, and you use the same perch to reach the switch.',
      'Take 1: jump, burst up and anchor while falling. Take 2: land on that echo, jump and burst up-right onto the shelf plate. Take 3: bounce off the anchored echo up-left into the switch, then run to the exit.',
    ],
    solution: [
      'go 11; j 24; b u; w 43; a 150; end',
      'go 10; until 140; j 24; b u; land 11; j 24; b ur; land 15.5; go 15.5; w 5s; end',
      'go 10; until 205; j 24; b u; land 11; k JL 24; w 10; b l; land; go 26',
    ],
    lore: 'Each of my selves could touch what the others could not. We learned to share the work instead of fighting over it.',
  },
  {
    id: 'w6-4',
    name: 'Relay of Selves',
    world: 6,
    objective: 'Pass the plates from self to self, then let go.',
    loopSeconds: 25,
    maxEchoes: 4,
    parEchoes: 3,
    parTime: 7,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '#..........#.........#.......#',
      '#..........#.........#.......#',
      '#..........#.........#.......#',
      '#..........#.........#.......#',
      E,
      E,
      E,
      '#....P.......................#',
      '#######..#####################',
      E,
      E,
      E,
      E,
      E,
      W,
      W,
    ],
    objects: [
      { type: 'veil', x: 7, y: 9, w: 2, h: 1, blocks: 'ghost' },
      { type: 'plate', id: 'a', x: 1, y: 8 },
      { type: 'plate', id: 'b', x: 12, y: 8 },
      { type: 'plate', id: 'c', x: 26, y: 8 },
      { type: 'door', x: 11, y: 5, w: 1, h: 4, open: 'a' },
      { type: 'door', x: 21, y: 5, w: 1, h: 4, open: 'b' },
      { type: 'door', x: 14, y: 10, w: 1, h: 5, open: 'c' },
      { type: 'door', x: 22, y: 10, w: 1, h: 5, open: '!a' },
      { type: 'shard', x: 3, y: 2 },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'You can drop through the pale floor to the corridor, but your echoes never can: their work is upstairs.',
      'Each upstairs door needs a self on its plate — and the last corridor door only opens while the first plate is empty.',
      'Hand the weight along: one echo holds the first plate, the next holds the second, the third walks through both doors to the far plate. Then the first one lets go.',
      'Take 1: sit on the far-left plate for 3 seconds, then step off. Take 2: go through the first door and sit on the plate behind it. Take 3: jump over it and go on to the far plate. Take 4: drop through the pale floor and run right.',
    ],
    solution: [
      'go 1; w 3s; go 5; end',
      'go 6; jr 16; go 12.5; w 6s; end',
      'w 40; go 6; jr 16; land; jr 24; land; go 26; w 6s; end',
      'go 7.5; land; until 200; go 26',
    ],
    lore: 'I passed the weight from self to self, like a lantern handed down a line. Then, one by one, I let go.',
  },
  {
    id: 'w6-5',
    name: 'Many Hands',
    world: 6,
    objective: 'Four selves, one way out.',
    loopSeconds: 30,
    maxEchoes: 4,
    parEchoes: 4,
    parTime: 13,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '#............#.........#.....#',
      '#............#.........#.....#',
      '#####........#.........#..####',
      '#............#.........#.....#',
      '#............#.........#.....#',
      '#............#.........#.....#',
      '#............#.........#.....#',
      '#............#.........#.....#',
      '#............#.........#.....#',
      '#............#.........#.....#',
      E,
      E,
      E,
      '#.......P....................#',
      W,
      W,
    ],
    objects: [
      { type: 'plate', id: 'g', x: 2, y: 2, w: 2, who: 'ghost' },
      { type: 'door', x: 13, y: 11, w: 1, h: 4, open: 'g' },
      { type: 'plate', id: 'b', x: 14, y: 14 },
      { type: 'door', x: 23, y: 11, w: 1, h: 4, open: 'b' },
      { type: 'veil', x: 24, y: 3, w: 2, h: 1, blocks: 'ghost' },
      { type: 'shard', x: 28, y: 5 },
      { type: 'exit', x: 28, y: 2 },
    ],
    hints: [
      'The pale plate sits on a shelf no self can reach alone, and only you can pass the pale hatch above the last room.',
      'Each door is held by a different echo, and two of your echoes must hang in the air as perches.',
      'Echo 1 anchors as a perch, echo 2 uses it to reach the pale plate, echo 3 holds the plate behind the first door, echo 4 anchors under the hatch for you.',
      'Take 1: jump, burst up, anchor while falling. Take 2: bounce off it and burst up-left onto the shelf. Take 3: go through the first door and sit on the plate. Take 4: go to the last room, jump, burst up and anchor under the hatch. Take 5: bounce off it and burst up through the hatch.',
    ],
    solution: [
      'go 6; j 24; b u; w 43; a 150; end',
      'go 5; until 140; j 24; b u; land 6; j 24; b ul; land 2.5; go 2.5; w 10s; end',
      'until 200; go 14; w 10s; end',
      'until 260; go 12.5; jr 20; land; go 24.5; j 24; b u; w 43; a 150; end',
      'until 330; go 12.5; jr 20; land; go 26; j 24; b u; land 24.5; j 24; b u; k R 20; land; go 28',
    ],
    lore: 'Many selves, one purpose. I held the Horologe for as long as I could, and what is left of that holding is you.',
  },
];
