import type { LevelDef } from '../core/types';

// World 7 — The Infinite Archive. Mastery: no new mechanics. Each level
// combines two or three familiar systems into one set piece, and the finale
// puts the whole cast of echoes to work at once.

const W = '##############################';

export const WORLD7: LevelDef[] = [
  {
    id: 'w7-1',
    name: 'Stone Bookmark',
    world: 7,
    objective: 'Ride the lift through the beam.',
    loopSeconds: 25,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 10,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '#.........................####',
      '#.........................####',
      '########################..####',
      '########################..####',
      '########################..####',
      '########################..####',
      '########################..####',
      '########################..####',
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#.............P..............#',
      '####...#################..####',
      W,
    ],
    objects: [
      { type: 'laser', x: 28, y: 12, dir: 'left' },
      { type: 'receiver', id: 'r', x: 1, y: 12 },
      { type: 'plate', id: 'p', x: 4, y: 15, w: 3 },
      { type: 'door', x: 4, y: 15, w: 3, h: 1, open: '!r' },
      { type: 'platform', x: 24, y: 15, w: 2, to: [[24, 3]], speed: 4, active: 'p' },
      { type: 'door', x: 23, y: 1, w: 1, h: 2, open: 'p' },
      { type: 'shard', x: 27, y: 10 },
      { type: 'exit', x: 2, y: 2 },
    ],
    hints: [
      'The beam crosses the lift shaft, and the pit only opens when the receiver goes dark.',
      'A stone remnant blocks a beam forever — but only on the far side from the emitter.',
      'Turn to stone between the emitter and the shaft, then let a second echo hold the plate.',
      'Take 1: stand right of the shaft (under the overhang) and jump into the beam. Take 2: sit in the pit on the plate. Take 3: ride the lift and roll left to the exit.',
    ],
    solution: [
      'go 26.5; j 24',
      'go 5; w 20s; end',
      'go 24.5; w 3.5s; go 2',
    ],
    lore: 'Every stone in these halls is shaped like me. I used to think they were statues.',
  },
  {
    id: 'w7-2',
    name: 'Hover Notes',
    world: 7,
    objective: 'Cross the gap, and keep the beam unbroken.',
    loopSeconds: 20,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 6,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '######################.......#',
      '######################.......#',
      '######################.......#',
      '######################.......#',
      '######################.......#',
      '######################.......#',
      '######################.......#',
      '#............................#',
      '#............................#',
      '#.P..........................#',
      '#####.................########',
      '#####..................#######',
      '#####.................########',
      '#####.................########',
      W,
      W,
    ],
    objects: [
      { type: 'laser', x: 4, y: 12, dir: 'right' },
      { type: 'receiver', id: 'r', x: 22, y: 12 },
      { type: 'shard', x: 23, y: 2 },
      { type: 'exit', x: 26, y: 1, active: 'r' },
    ],
    hints: [
      'The gap is far too wide for one leap, and the exit only glows while the beam reaches its receiver.',
      'An anchored echo is a springy stepping stone in mid-air. Landing on it recharges your jump and burst.',
      'If a stepping stone falls into the beam it turns to stone and cuts the power. End that take while it still hovers.',
      'Take 1: jump, burst right and anchor above the middle of the gap, then press R before the anchor runs out. Take 2: hop across on it and wait under the exit. Take 3: hop across, ghost-bounce off take 2 and burst up.',
    ],
    solution: [
      'go 1; r 22; jr 10; k R 10; b r; r 20; a 140; end',
      'go 1; w 30; r 22; jr 12; k R 4; b r; r 20; land; jr 8; b r; r 10; land; go 26; w 10s; end',
      'go 1; w 60; r 22; jr 12; k R 4; b r; r 20; land; jr 8; b r; r 10; land; go 24; j 20; land 26; j 36; w 5; b u; w 60',
    ],
    lore: "The Archivist's notes are in my handwriting. I keep finding margins I don't remember writing.",
  },
  {
    id: 'w7-3',
    name: 'Doorstop',
    world: 7,
    objective: 'Keep the beam flowing until the lift reaches the top.',
    loopSeconds: 20,
    maxEchoes: 2,
    parEchoes: 2,
    parTime: 8,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '#...........................##',
      '###########################.##',
      '##........................#.##',
      '##........................#.##',
      '##........................#.##',
      '##........................#.##',
      '##........................#.##',
      '##........................#.##',
      '#.........................#.##',
      '#.........................#.##',
      '#.........................#.##',
      '#.........................#.##',
      '#.........................#.##',
      '#.............P.............##',
      '###########################.##',
      W,
    ],
    objects: [
      { type: 'laser', x: 0, y: 10, dir: 'right' },
      { type: 'door', x: 1, y: 9, w: 1, h: 6, open: 's' },
      { type: 'switch', id: 's', x: 23, y: 7, who: 'ghost', timer: 0.6 },
      { type: 'receiver', id: 'r', x: 20, y: 10 },
      { type: 'platform', x: 27, y: 15, w: 1, to: [[27, 2]], speed: 4, active: 'r' },
      { type: 'shard', x: 2, y: 4 },
      { type: 'exit', x: 20, y: 1 },
    ],
    hints: [
      'The lift only climbs while the beam reaches its receiver, and the shutter by the emitter only opens for a moment.',
      'That switch answers only to echoes. And a door can never close while a ball sits inside it.',
      'One echo flips the switch; another waits against the shutter and rolls into the doorway the instant it opens.',
      'Take 1: stand under the switch, jump and burst up into it. Take 2: roll left against the shutter and keep holding left. Take 3: step into the lift tunnel on the right and ride it to the top.',
    ],
    solution: [
      'go 23; w 30; j 24; b u; w 60; end',
      'go 2; l 6s; w 12s; end',
      'go 27; w 4s; go 20',
    ],
    lore: 'Someone once propped this door open with their own shadow. I know the trick. My body knew it before I did.',
  },
  {
    id: 'w7-4',
    name: 'Relay of Selves',
    world: 7,
    objective: 'Pass the baton: open every gate for the one behind you.',
    loopSeconds: 25,
    maxEchoes: 4,
    parEchoes: 3,
    parTime: 8,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      '#......##########....###.....#',
      '#......##########....###.....#',
      '#......####..####....###.....#',
      '#......####..####....###.....#',
      '#......####..####....###.....#',
      '#......####..####....###.....#',
      '#......#.##..##.#....#.#.....#',
      '#......#.#....#.#....#.#.....#',
      '#......#.#....#.#....#.#.....#',
      '#......#.#....#.#....#.#.....#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#....P.......................#',
      W,
      W,
    ],
    objects: [
      { type: 'spring', x: 2, y: 14 },
      { type: 'switch', id: 'a', x: 2, y: 3, who: 'ghost', timer: 4 },
      { type: 'platform', x: 8, y: 11, w: 1, h: 4, to: [[8, 7]], speed: 8, hazard: true, active: 'a' },
      { type: 'breakable', x: 11, y: 8, w: 2, h: 1 },
      { type: 'switch', id: 'b', x: 11, y: 7, who: 'ghost', timer: 4 },
      { type: 'platform', x: 15, y: 11, w: 1, h: 4, to: [[15, 7]], speed: 8, hazard: true, active: 'b' },
      { type: 'fan', x: 18, y: 3, w: 1, h: 12, dir: 'up' },
      { type: 'switch', id: 'c', x: 18, y: 3, who: 'ghost', timer: 4 },
      { type: 'platform', x: 22, y: 11, w: 1, h: 4, to: [[22, 7]], speed: 8, hazard: true, active: 'c' },
      { type: 'exit', x: 27, y: 14 },
    ],
    hints: [
      'Each gate lifts only while its switch is lit, and those switches answer only to echoes.',
      'An echo can never pass a gate it opened itself: while you recorded it, nothing happened. Open the way for whoever comes next.',
      'Record the relay in order: the switch above the spring, then the one behind the cracked ceiling, then the one at the top of the updraft. Everyone else waits by the gates.',
      'Take 1: roll onto the spring and burst up into the switch. Take 2: wait by the first gate, go through, then jump and burst up through the cracked ceiling. Take 3: follow through both gates and ride the updraft. Take 4: follow the relay to the exit.',
    ],
    solution: [
      'go 2; w 25; b u; w 60; end',
      'go 6.5; until 100; go 11; j 24; b u; w 60; end',
      'go 6.5; until 100; go 13; w 60; go 18; w 3s; end',
      'go 6.5; until 100; go 13; w 60; go 21; w 60; go 27',
    ],
    lore: 'Every gate here was built to be opened by whoever came before. The Archivist never locked me out. They were holding the doors.',
  },
  {
    id: 'w7-5',
    name: 'The Horologe',
    world: 7,
    objective: 'Bring every past self together and wind the Horologe.',
    loopSeconds: 25,
    maxEchoes: 5,
    parEchoes: 4,
    parTime: 9,
    abilities: ['burst', 'anchor'],
    map: [
      W,
      W,
      '#............................#',
      '#............................#',
      '#............................#',
      '####.................###..####',
      '####.................###..####',
      '####.................###..####',
      '########################..####',
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#.............P..............#',
      '####...#################..####',
      W,
    ],
    objects: [
      { type: 'laser', x: 28, y: 12, dir: 'left' },
      { type: 'receiver', id: 'r', x: 1, y: 12 },
      { type: 'plate', id: 'p', x: 4, y: 15, w: 3 },
      { type: 'door', x: 4, y: 15, w: 3, h: 1, open: '!r' },
      { type: 'platform', x: 24, y: 15, w: 2, to: [[24, 5]], speed: 4, active: 'p' },
      { type: 'door', x: 24, y: 8, w: 2, h: 1, open: 'p' },
      { type: 'laser', x: 21, y: 6, dir: 'left' },
      { type: 'switch', id: 'c', x: 10, y: 11, who: 'ghost', timer: 2 },
      { type: 'shard', x: 8, y: 2 },
      { type: 'exit', x: 2, y: 4, active: 'p & c' },
    ],
    hints: [
      'Four jobs at once: the beam across the lift, the pit plate, the chasm and the bell switch. One self for each.',
      'Turn to stone right of the shaft to darken the beam. That opens the pit, and the plate inside drives the lift and unseals the ceiling.',
      'A past self can ride the lift beside you, leap out first and anchor over the chasm. The exit only glows while the plate is held and the bell has just been rung by an echo.',
      'Take 1: jump into the beam right of the shaft. Take 2: sit on the pit plate. Take 3: wait a moment, ride the left half of the lift, then jump, burst left and anchor over the chasm. Take 4: wait under the bell switch and jump into it about 7 s in. Take 5: ride the right half of the lift, hop across on your anchored echo and roll into the exit.',
    ],
    solution: [
      'go 26.5; j 24',
      'go 5; w 20s; end',
      'w 20; go 24.1; until 300; go 24; l 22; jl 10; k L 10; b l; l 20; a 140; end',
      'w 60; go 10; until 420; j 24; w 60; end',
      'go 25.1; until 330; go 24; l 22; jl 12; k L 4; b l; l 20; land; jl 8; b l; l 10; land; go 2',
    ],
    lore: 'I was never just waking up. I am the Archivist’s last echo, and every self I kept was a hand on the key. Listen: the Horologe is ticking again.',
  },
];
