import type { LevelDef } from '../core/types';

// World 1 — First Echo. Movement, recording, replay, plates, doors,
// bouncing off echoes, and a first toggle switch.

const W = '##############################';
const E = '#............................#';

export const WORLD1: LevelDef[] = [
  {
    id: 'w1-1',
    name: 'Wake',
    world: 1,
    objective: 'Reach the light.',
    loopSeconds: 30,
    maxEchoes: 0,
    parEchoes: 0,
    parTime: 6,
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      E,
      E,
      E,
      E,
      '#............................#',
      '#............................#',
      '#....................#########',
      '#.............##.....#########',
      '#..P.....#....##.....#########',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 4, y: 11, text: '← → roll' },
      { type: 'sign', x: 10, y: 10, text: 'Space: jump — hold for height' },
      { type: 'shard', x: 14, y: 9 },
      { type: 'exit', x: 26, y: 11 },
    ],
    hints: [
      'The glowing ring is the exit.',
      'Holding jump longer makes you jump higher.',
      'The tall block needs a full, held jump.',
      'Something glitters high above the middle block — jump straight up from its top.',
    ],
    solution: ['go 7.5; jr 24; go 12.5; jr 24; go 14.5; j 24; settle; go 19; jr 24; go 26'],
    lore: 'I woke inside the Horologe with no memory — only the echo of a bounce, repeating somewhere far away.',
  },
  {
    id: 'w1-2',
    name: 'First Echo',
    world: 1,
    objective: 'Open the door and reach the exit.',
    loopSeconds: 20,
    maxEchoes: 1,
    parEchoes: 1,
    parTime: 4,
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      E,
      '#.................#..........#',
      '#.................#..........#',
      '#.................#..........#',
      '#.................#..........#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#..P.........................#',
      W,
      W,
    ],
    objects: [
      { type: 'plate', id: 'p', x: 6, y: 14, w: 2 },
      { type: 'door', x: 18, y: 11, w: 1, h: 4, open: 'p' },
      { type: 'sign', x: 7, y: 11, text: 'Plates hold doors open only while pressed' },
      { type: 'sign', x: 7, y: 9, text: 'R: end this take — your echo will repeat it' },
      { type: 'exit', x: 25, y: 14 },
    ],
    hints: [
      'The door stays open only while something presses the plate.',
      'Your past self can press the plate for you.',
      'Rest on the plate, then press R. Your echo will replay that.',
      'Take 1: sit on the plate for a few seconds, press R. Take 2: run to the exit.',
    ],
    solution: ['go 6.5; w 5s; end', 'go 25'],
  },
  {
    id: 'w1-3',
    name: 'Ghost Bounce',
    world: 1,
    objective: 'Climb to the exit on the high ledge.',
    loopSeconds: 20,
    maxEchoes: 1,
    parEchoes: 1,
    parTime: 4,
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      E,
      E,
      E,
      '#.................############',
      '#.................############',
      '#.................############',
      '#.................############',
      '#.................############',
      '#..P..............############',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 8, y: 10, text: 'Echoes are springy — bounce on them!' },
      { type: 'sign', x: 8, y: 11, text: 'Jump as you land on one to soar' },
      { type: 'shard', x: 12, y: 8 },
      { type: 'exit', x: 25, y: 8 },
    ],
    hints: [
      'The ledge is higher than any jump.',
      'Echoes are solid and springy to you.',
      'Leave an echo waiting next to the wall, then jump onto it.',
      'Take 1: go next to the wall and wait. Take 2: jump onto your echo and press jump again as you land.',
    ],
    solution: ['go 15; w 6s; end', 'go 13.5; j 20; land 15; jr 30; go 25'],
    lore: 'The Horologe keeps every moment it has ever measured. Nothing here is ever truly lost.',
  },
  {
    id: 'w1-4',
    name: 'Two Keys',
    world: 1,
    objective: 'Both doors must be open at once.',
    loopSeconds: 20,
    maxEchoes: 2,
    parEchoes: 2,
    parTime: 4,
    map: [
      W,
      E,
      E,
      E,
      E,
      E,
      E,
      '#...............#.....#......#',
      '#...............#.....#......#',
      '#...............#.....#......#',
      '#...............#.....#......#',
      '#............................#',
      '#.#####......................#',
      '#............................#',
      '#..P.........................#',
      W,
      W,
    ],
    objects: [
      { type: 'plate', id: 'a', x: 8, y: 14 },
      { type: 'plate', id: 'b', x: 3, y: 11 },
      { type: 'door', x: 16, y: 11, w: 1, h: 4, open: 'a' },
      { type: 'door', x: 22, y: 11, w: 1, h: 4, open: 'b' },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'Each door has its own plate.',
      'One echo can only press one plate at a time.',
      'Record one echo on each plate.',
      'Take 1: sit on the floor plate. Take 2: jump up onto the ledge plate. Take 3: run.',
    ],
    solution: ['go 8; w 6s; end', 'go 8.5; jl 24; land; go 3; w 5s; end', 'go 26'],
  },
  {
    id: 'w1-5',
    name: 'High Switch',
    world: 1,
    objective: 'Hit the switch and hold the plate.',
    loopSeconds: 25,
    maxEchoes: 2,
    parEchoes: 1,
    parTime: 7,
    map: [
      W,
      '#.......................#....#',
      '#.......................#....#',
      '#.......................#....#',
      '#.......................#....#',
      '#.......................#....#',
      '#.......................#....#',
      '#.......................#....#',
      '#.......................#....#',
      E,
      E,
      E,
      E,
      E,
      '#..P.........................#',
      W,
      W,
    ],
    objects: [
      { type: 'switch', id: 's', x: 12, y: 8 },
      { type: 'plate', id: 'p', x: 20, y: 14 },
      { type: 'door', x: 24, y: 9, w: 1, h: 6, open: 's & p' },
      { type: 'sign', x: 12, y: 11, text: 'Switches stay flipped' },
      { type: 'shard', x: 27, y: 3 },
      { type: 'exit', x: 27, y: 14 },
    ],
    hints: [
      'The switch is too high to reach with a normal jump.',
      'Bounce off an echo to reach it — and the plate still needs weight.',
      'A single echo can do two jobs if it moves between them at the right time.',
      'Take 1: wait under the switch for about 3 seconds, then go sit on the plate. Take 2: bounce off your echo into the switch, then head for the exit.',
    ],
    solution: ['go 12; w 3s; go 20; w 8s; end', 'go 10.5; j 20; land 12; j 30; go 23; w 60; go 27'],
    lore: 'Each echo is a promise you made to yourself. Keep enough of them, and a door opens.',
  },
];
