import type { LevelDef } from '../core/types';

// World 4 — Temporal Machinery. Timed switches, inverted door logic, always-
// moving platforms, synchronised echoes, and an echo's fade-out as a trigger.

const W = '##############################';

export const WORLD4: LevelDef[] = [
  {
    id: 'w4-1',
    name: 'Relay',
    world: 4,
    objective: 'Pass the baton: open the way for the one behind you.',
    loopSeconds: 20,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 7.5,
    abilities: ['burst'],
    map: [
      W,
      '##################.###########',
      '#............................#',
      '#............................#',
      '#............................#',
      '#...P........................#',
      '#.############..##########.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      '#.#########............###.###',
      W,
    ],
    objects: [
      { type: 'switch', id: 'a', x: 1, y: 11, timer: 2 },
      { type: 'switch', id: 'b', x: 26, y: 11, timer: 2 },
      { type: 'door', x: 10, y: 2, w: 1, h: 4, open: 'a' },
      { type: 'door', x: 14, y: 6, w: 2, h: 1, open: 'b' },
      { type: 'sign', x: 5, y: 3, text: 'Timed switches stay on only for a moment' },
      { type: 'shard', x: 18, y: 1 },
      { type: 'exit', x: 20, y: 15 },
    ],
    hints: [
      'Each shaft is one-way: whoever drops in stays there.',
      'A falling echo flips the switch in its shaft — the door stays open only two seconds.',
      'The echo that opens the hatch must get through the first door too, at the same time as you.',
      'Take 1: drop into the left shaft after ~1 s. Take 2: wait at the door, go through, drop into the right shaft two seconds later. Take 3: follow, stand on the hatch.',
    ],
    solution: [
      'w 1s; go 1; w 1s; end',
      'go 9; until 2.2s; go 25; until 4s; go 26; w 1s; end',
      'go 8; until 2.2s; go 14.5; until 5.1s; go 20; land 20; go 20',
    ],
    lore: 'Every gear in the Horologe turns the next one. None of them has ever seen the whole machine.',
  },
  {
    id: 'w4-2',
    name: 'Counterweights',
    world: 4,
    objective: 'Three doors, three moments. Choose when each weight lifts.',
    loopSeconds: 15,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 8.5,
    abilities: ['burst'],
    map: [
      W,
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#.....P......................#',
      '##.########.###############.##',
      '##.########.###############.##',
      '##.########.###############.##',
      '##.########.###############.##',
      '##.########.###############.##',
      '##.########...............#.##',
      '##.########...............#.##',
      '##.########...............#.##',
      '##.########...............#.##',
      W,
    ],
    objects: [
      { type: 'plate', id: 'p', x: 2, y: 15 },
      { type: 'plate', id: 'q', x: 27, y: 15 },
      { type: 'door', x: 14, y: 12, w: 1, h: 4, open: 'p & !q' },
      { type: 'door', x: 18, y: 12, w: 1, h: 4, open: 'q & !p' },
      { type: 'door', x: 22, y: 12, w: 1, h: 4, open: '!p & !q' },
      { type: 'sign', x: 14, y: 3, text: 'A weight leaves its well only when its take ends' },
      { type: 'exit', x: 24, y: 15 },
    ],
    hints: [
      'Nobody climbs out of a well. An echo leaves its plate only when its recording ends.',
      'Read the doors: the first wants P without Q, the second Q without P, the last wants both wells empty.',
      'The echo in P must arrive first and leave first; the echo in Q arrives after you pass the first door and leaves last.',
      'Take 1: drop into the left well at once and squash (↓), press R after ~4 s. Take 2: wait ~2.5 s, drop into the right well, press R after ~5.5 s. Take 3: drop into the tunnel and walk through each door as it opens.',
    ],
    solution: [
      'go 2; sq 40; until 4s; end',
      'until 2.5s; go 10; jr 12; go 27; sq 40; until 5.5s; end',
      'go 11; land 11; until 1.7s; go 16; until 4.2s; go 20; until 5.7s; go 24',
    ],
  },
  {
    id: 'w4-3',
    name: 'Gear Ratio',
    world: 4,
    objective: 'Two lifts, two lamps. The hatch opens only when both are lit.',
    loopSeconds: 12,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 12,
    abilities: ['burst'],
    map: [
      W,
      '######..###############..#####',
      '######..###############..#####',
      '######..###############..#####',
      '######..###############..#####',
      '######..###############..#####',
      '######..###############..#####',
      '#............................#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#...........P................#',
      '##############..##############',
      '#............................#',
      '#............................#',
      '#............................#',
      W,
    ],
    objects: [
      { type: 'platform', x: 6, y: 3, w: 2, to: [[6, 10.5]], speed: 4.6875 },
      { type: 'platform', x: 23, y: 3, w: 2, to: [[23, 10.5]], speed: 3.125 },
      { type: 'switch', id: 'a', x: 6.5, y: 2, timer: 1.2 },
      { type: 'switch', id: 'b', x: 23.5, y: 2, timer: 1.2 },
      { type: 'door', x: 14, y: 12, w: 2, h: 1, open: 'a & b' },
      { type: 'sign', x: 14, y: 8, text: 'These lifts never stop — each keeps its own time' },
      { type: 'exit', x: 18, y: 15 },
    ],
    hints: [
      'Only a rider on a lift can reach the lamp at the top of its shaft.',
      'The lifts run at different speeds, so their lamps flash to different rhythms.',
      'Put an echo on each lift, then watch for the one moment both lamps are lit together.',
      'Take 1: hop on the left lift as it comes down (~1.3 s). Take 2: hop on the right lift (~2 s). Take 3: stand on the hatch — the lamps line up at about 9.5 s.',
    ],
    solution: [
      'go 4.5; until 1.3s; j 12; land 6.5; go 6.5; w 10s; end',
      'go 25.5; until 2.1s; j 12; land 23.5; go 23.5; w 10s; end',
      'go 14.5; until 9.7s; go 18; land 18; go 18',
    ],
  },
  {
    id: 'w4-4',
    name: 'Three Bells',
    world: 4,
    objective: 'Ring all three bells in the same moment.',
    loopSeconds: 10,
    maxEchoes: 4,
    parEchoes: 3,
    parTime: 4.2,
    abilities: ['burst'],
    map: [
      W,
      W,
      W,
      W,
      W,
      W,
      '#################...##########',
      '#####..........##...##########',
      '#####..........##...##########',
      '#############..##...##########',
      '#########....................#',
      '#########....................#',
      '#########............#########',
      '#########....................#',
      '#............................#',
      '#...............P............#',
      W,
    ],
    objects: [
      { type: 'switch', id: 'a', x: 1, y: 15, timer: 1 },
      { type: 'switch', id: 'b', x: 28, y: 11, timer: 1 },
      { type: 'switch', id: 'c', x: 5, y: 8, timer: 1 },
      { type: 'door', x: 8, y: 14, w: 1, h: 2, open: '!a' },
      { type: 'door', x: 21, y: 10, w: 1, h: 2, open: '!b' },
      { type: 'door', x: 13, y: 9, w: 2, h: 1, open: '!c' },
      { type: 'door', x: 21, y: 13, w: 1, h: 3, open: 'a & b & c' },
      { type: 'sign', x: 16, y: 12, text: 'A bell locks its door behind whoever rings it' },
      { type: 'shard', x: 18, y: 6 },
      { type: 'exit', x: 27, y: 15 },
    ],
    hints: [
      'Ringing a bell slams its door behind the ringer until the bell falls silent.',
      'The gate wants all three bells ringing at once. Nobody can ring two, and each rings for only a second.',
      'Pick one moment, say 2.5 seconds in, and have every echo ring its bell right then. The high bells need a jump and a burst.',
      'Take 1: roll into the low left bell. Take 2: jump and burst up-right into the high right bell. Take 3: jump and burst straight up through the ceiling hatch, then roll left. All three ring at ~2.5 s. Take 4: wait at the gate.',
    ],
    solution: [
      'w 35; go 1; w 1s; end',
      'w 58; go 19; j 24; b ur; go 28; w 1s; end',
      'w 32; go 13.5; j 24; b u; l 30; go 5; w 1s; end',
      'go 20; until 2.55s; go 27',
    ],
    lore: 'Three bells, one stroke. The Horologe was built to keep many moments in step — lately they drift apart.',
  },
  {
    id: 'w4-5',
    name: 'Mainspring',
    world: 4,
    objective: 'Every gear in its place, every echo at its moment.',
    loopSeconds: 12,
    maxEchoes: 5,
    parEchoes: 4,
    parTime: 10.5,
    abilities: ['burst'],
    map: [
      W,
      '#..........#.................#',
      '#..........#.................#',
      '#..........#.........#########',
      '#....P.....#.........#########',
      '#.#######..#.........#########',
      '#.######.............#########',
      '#.######.............#########',
      '#.######.............#########',
      '#.#..................#########',
      '#.#..................#########',
      '#.#..................#########',
      '#.##.####..###################',
      '#.##.#...............#########',
      '#.##.#...............#########',
      '#.##.#...............#########',
      W,
    ],
    objects: [
      { type: 'plate', id: 'w', x: 1, y: 15 },
      { type: 'door', x: 9, y: 5, w: 2, h: 1, open: 'w' },
      { type: 'door', x: 7, y: 9, w: 1, h: 3, open: '!w' },
      { type: 'platform', x: 4, y: 12, w: 1, to: [[4, 15.5]], speed: 2.5 },
      { type: 'switch', id: 'l', x: 4, y: 15, timer: 0.8, who: 'ghost' },
      { type: 'switch', id: 'b', x: 28, y: 2, timer: 1.5 },
      { type: 'door', x: 21, y: 1, w: 1, h: 2, open: '!b' },
      { type: 'plate', id: 't', x: 20, y: 11, who: 'ghost' },
      { type: 'door', x: 9, y: 12, w: 2, h: 1, open: 'b & l & t' },
      { type: 'sign', x: 15, y: 8, text: 'Marked plates and lamps answer only to echoes' },
      { type: 'shard', x: 25, y: 1 },
      { type: 'exit', x: 18, y: 15 },
    ],
    hints: [
      'Four jobs: a weight in the well, a lamp at the bottom of the plunger, a bell far above, and someone standing on the plate under it.',
      'The weight opens the hatch for everyone else — and only when it fades does the plunger room open.',
      'The bell is out of reach without a ghost bounce, and the plunger lights its lamp only at the bottom of each stroke. Ring the bell as the lamp lights.',
      'Take 1: drop into the well, press R at ~4 s. Take 2: stand on the plate under the bell. Take 3: bounce off take 2 and burst up-right into the bell at ~7 s. Take 4: after the weight fades, drop into the plunger pit. Take 5: wait on the floor hatch.',
    ],
    solution: [
      'go 1; sq 30; until 4s; end',
      'go 9.5; until 1.4s; land; go 20; sq 20; until 8.5s; end',
      'go 9.5; until 1.4s; land; go 18.3; until 4.63s; j 20; land 20; jr 30; b ur; go 28; w 2s; end',
      'go 9.5; until 1.4s; land; go 8; until 4.1s; go 4; w 6s; end',
      'go 9.5; until 1.4s; land; go 9.5; until 7.4s; go 18; land 18; go 18',
    ],
    lore: 'I found the mainspring. It is almost unwound, and every echo I keep turns it a little tighter.',
  },
];
