import type { LevelDef } from '../core/types';

// World 5 — The Living Maze. Hazards and sacrifice: spikes, lasers,
// receivers, patrolling sentinels and fans. A take that ends in stone can be
// kept as an echo, and its remnant stays for the rest of the loop: a stepping
// stone, a shield, a weight. Failure as progress.

const W = '##############################';

export const WORLD5: LevelDef[] = [
  {
    id: 'w5-1',
    name: 'Stepping Stones',
    world: 5,
    objective: 'Cross the thorn pit.',
    loopSeconds: 20,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 3.2,
    abilities: ['burst'],
    map: [
      W,
      W,
      W,
      W,
      W,
      W,
      W,
      W,
      W,
      '###################.##########',
      '###################.##########',
      '###################.##########',
      '#............................#',
      '#.P..........................#',
      '####^^^^^^^^^^^^^^^^^^^^^#####',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 2, y: 12, text: 'Keep a fall as an echo — its stone stays' },
      { type: 'shard', x: 19, y: 9 },
      { type: 'exit', x: 27, y: 13 },
    ],
    hints: [
      'Whatever touches the thorns turns to stone — and stays there.',
      'A take that ends in stone can still be kept. Its remnant is solid ground for you.',
      'Each stone is a place to land, jump and burst again. The pit needs two of them.',
      'Take 1: jump, burst right, and let yourself fall a third of the way. Take 2: skip off that stone, fall two thirds of the way. Take 3: hop stone to stone.',
    ],
    solution: [
      'r 8; jr 4; b r; l 10; w 200',
      'w 30; r 8; jr 4; b r; land 9; jr 6; b r; l 4; w 200',
      'w 60; r 8; jr 4; b r; land 9; jr 10; b r; land; jr 6; b r; r 30; go 27',
    ],
    lore: 'The halls are full of stones shaped like me. I thought they were failures. They were kept on purpose — every one of them a way across.',
  },
  {
    id: 'w5-2',
    name: 'Stone Shield',
    world: 5,
    objective: 'Get past both beams.',
    loopSeconds: 20,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 6.5,
    abilities: ['burst'],
    map: [
      W,
      '################.............#',
      '################.............#',
      '######################.......#',
      '######################.......#',
      '######################..######',
      '#########.############..######',
      '#....................#..######',
      '#....................#..######',
      '#....................#..######',
      '#.......................######',
      '#....................#..######',
      '#....................#..######',
      '#....................#..######',
      '#.P.....................######',
      W,
      W,
    ],
    objects: [
      { type: 'laser', x: 9, y: 6, dir: 'down' },
      { type: 'laser', x: 21, y: 10, dir: 'right' },
      { type: 'fan', x: 22, y: 5, w: 2, h: 10, dir: 'up' },
      { type: 'sign', x: 5, y: 9, text: 'Stone blocks a beam — for the rest of the loop' },
      { type: 'sign', x: 18, y: 13, text: 'Fans lift you' },
      { type: 'shard', x: 16, y: 2 },
      { type: 'exit', x: 27, y: 4 },
    ],
    hints: [
      'A beam stops at the first thing it touches. Behind a stone, it is dark.',
      'A stone only shields what lies beyond it. You pass under the first one, and beside the second.',
      'Freeze high in the curtain so you can roll beneath. In the shaft, freeze against the emitter wall and rise along the far wall.',
      'Take 1: jump up next to the curtain and drift into it. Take 2: roll under that stone, ride the fan hugging the left wall. Take 3: ride the fan along the right wall and go to the exit.',
    ],
    solution: ['go 8.5; j 24; w 6; r 40; w 300', 'w 50; go 22; w 15; l 300', 'w 60; go 23; w 50; go 27'],
    lore: 'A beam cannot pass through what I left behind. My old mistakes stand between me and the light, like a hand held over a candle.',
  },
  {
    id: 'w5-3',
    name: 'Tripwire',
    world: 5,
    objective: 'Read the wires. Break them in the right order.',
    loopSeconds: 20,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 5,
    abilities: ['burst'],
    map: [
      W,
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#..................###########',
      '#...................##########',
      '#...................####.#####',
      '#.P..........................#',
      W,
      W,
    ],
    objects: [
      { type: 'laser', x: 1, y: 11, dir: 'right' },
      { type: 'receiver', id: 'c', x: 6, y: 11 },
      { type: 'laser', x: 1, y: 5, dir: 'right' },
      { type: 'receiver', id: 'a', x: 9, y: 5 },
      { type: 'door', x: 19, y: 12, w: 1, h: 3, open: 'a & !c' },
      { type: 'sign', x: 12, y: 12, text: 'Receivers signal while a beam reaches them' },
      { type: 'laser', x: 24, y: 13, dir: 'down', active: 'a' },
      { type: 'exit', x: 27, y: 14 },
    ],
    hints: [
      'The door wants wire A lit and wire C dark. The light at the exit only goes out when wire A goes dark.',
      'A stone in a beam darkens its receiver for the rest of the loop — and it can never be lit again.',
      'Order matters: break C first, get past the door while A is still lit, then have A broken behind you.',
      'Take 1: jump into the low beam. Take 2: wait a moment, jump and burst onto the low receiver, then jump and burst up into the high beam. Take 3: run through the door and wait before the light until it goes out.',
    ],
    solution: ['go 4.5; j 24; w 100', 'w 30; go 7.5; j 24; w 10; b ul; land 6; w 10; j 24; w 12; b u; w 100', 'go 22; w 45; go 27'],
  },
  {
    id: 'w5-4',
    name: 'Sentinels',
    world: 5,
    objective: 'Hold both plates and slip past the sentinels.',
    loopSeconds: 25,
    maxEchoes: 3,
    parEchoes: 2,
    parTime: 10,
    abilities: ['burst'],
    map: [
      W,
      '#.......................######',
      '#.......................######',
      '#.......................######',
      '#.......................######',
      '#.......................######',
      '#.......................######',
      '#..............#######..######',
      '#.......................######',
      '#.......................######',
      '#..######...............######',
      '#............................#',
      '#............................#',
      '#............................#',
      '#.P..........................#',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 12, y: 11, text: 'Sentinels turn whatever they touch to stone' },
      { type: 'plate', id: 'p', x: 5, y: 9 },
      { type: 'platform', x: 4, y: 9, w: 1, h: 1, to: [[6, 9]], speed: 2, hazard: true },
      { type: 'plate', id: 'q', x: 18, y: 6 },
      { type: 'platform', x: 17, y: 6, w: 1, h: 1, to: [[19, 6]], speed: 2, hazard: true },
      { type: 'platform', x: 4, y: 13, w: 1, h: 2, to: [[22, 13]], speed: 5, hazard: true },
      { type: 'door', x: 24, y: 11, w: 1, h: 4, open: 'p & q' },
      { type: 'platform', x: 26, y: 11, w: 1, h: 1, to: [[26, 14]], speed: 3, hazard: true },
      { type: 'shard', x: 3, y: 2 },
      { type: 'exit', x: 28, y: 14 },
    ],
    hints: [
      'Both plates sit where a sentinel walks. Nothing living can stay on them for long.',
      'You do not have to survive on a plate. A stone weighs just as much as you do.',
      'Let one echo be caught on each plate. The low ledge has quiet ends on both sides of its sentinel; the high ledge is a leap from the right end of the low one. Then jump the floor sentinel head-on and wait for the crusher to rise.',
      'Take 1: after a moment, climb from the far left onto the low ledge and sit on its plate. Take 2: follow the floor sentinel right, climb onto the right end of the low ledge, leap to the high ledge and sit on its plate. Take 3: meet the floor sentinel head-on, jump it, wait at the door, pass under the crusher.',
    ],
    solution: [
      'w 80; go 1; j 24; w 4; b u; w 8; land 5; go 5; w 600',
      'w 100; go 9.5; j 24; w 4; b u; land 8; go 8; w 20; r 8; jr 24; b r; land 16; go 18; w 600',
      'until 230; r 66; jr 30; go 23; until 450; go 28',
    ],
    lore: 'Some of the stones here are still smiling. They stood where no one could stand, and held the doors for whoever came after.',
  },
  {
    id: 'w5-5',
    name: 'The Living Maze',
    world: 5,
    objective: 'Find the way out of the maze.',
    loopSeconds: 30,
    maxEchoes: 4,
    parEchoes: 3,
    parTime: 11.5,
    abilities: ['burst'],
    map: [
      W,
      '############.......###########',
      '#...........................##',
      '#...........................##',
      '#...........................##',
      '##########################..##',
      '####################.#####..##',
      '################.........#..##',
      '################.........#..##',
      '################.........#..##',
      '################.........#..##',
      '################.........#..##',
      '#...........................##',
      '#.P.........................##',
      '####^^^^^^^^^^^^##############',
      W,
      W,
    ],
    objects: [
      { type: 'laser', x: 20, y: 6, dir: 'down' },
      { type: 'fan', x: 26, y: 5, w: 2, h: 9, dir: 'up' },
      { type: 'platform', x: 9, y: 4, w: 1, h: 1, to: [[24, 4]], speed: 4, hazard: true },
      { type: 'laser', x: 12, y: 1, dir: 'right' },
      { type: 'receiver', id: 'r', x: 16, y: 1 },
      { type: 'door', x: 7, y: 2, w: 1, h: 3, open: '!r' },
      { type: 'shard', x: 15, y: 1 },
      { type: 'exit', x: 2, y: 4 },
    ],
    hints: [
      'Thorns, a curtain of light, a beam feeding the last door. Each needs someone to fall there first.',
      'Every stone you leave is still there for the next take: a step, a shield, a broken wire.',
      'One stone in the pit, one high in the curtain, one in the beam above the upper hall. The sentinel can be jumped head-on — but never jump right under the live beam.',
      'Take 1: fall a third of the way into the pit. Take 2: skip off it and jump into the curtain from just before it. Take 3: cross, ride the fan, wait for the sentinel to pass, jump into the beam. Take 4: follow, hop the sentinel, walk out.',
    ],
    solution: [
      'r 8; jr 4; b r; l 10; w 200',
      'w 30; r 8; jr 4; b r; land 9; jr 6; b r; land 17; go 18.5; j 24; r 30; w 200',
      'w 90; r 8; jr 4; b r; land 9; jr 6; b r; land 17; go 26.5; w 30; go 22; until 380; go 14; j 24; w 300',
      'w 150; r 8; jr 4; b r; land 9; jr 6; b r; land 17; go 26.5; w 30; go 22; until 410; l 70; jl 8; go 2',
    ],
    lore: 'The Archivist never swept the stones away. "A record is not a loss," the moss-covered plaque reads. "Keep them, and the maze remembers the way out."',
  },
];
