import type { LevelDef } from '../core/types';

// World 3 — Momentum Lab. Rubber floors, springs, the BURST ability, cracked
// and heavy breakables, and momentum passed between balls. Heavy breakables
// (strength 900) cannot be broken by anything a ball does alone (burst 640,
// side spring 860, bounces off resting echoes < 830, and fast speeds bleed
// off quickly): only speed borrowed from a moving echo (a ram or a catapult,
// ~1100 px/s) gets through, and only when the wall is within ~3-4 tiles.

const W = '##############################';

export const WORLD3: LevelDef[] = [
  {
    id: 'w3-1',
    name: 'Spring Loaded',
    world: 3,
    objective: 'Reach the exit on top of the tower.',
    loopSeconds: 20,
    maxEchoes: 1,
    parEchoes: 1,
    parTime: 6.5,
    map: [
      W,
      '#............................#',
      '#............................#',
      '#.................############',
      '#.................############',
      '#.................############',
      '#.................############',
      '#.................############',
      '#.............##..############',
      '#.................############',
      '#.................############',
      '#........##.......############',
      '#........##.......############',
      '#........##.......############',
      '#..P.....#####....############',
      '####=====#####################',
      W,
    ],
    objects: [
      { type: 'sign', x: 5, y: 10, text: 'Rubber (=): jump on it to fly high' },
      { type: 'sign', x: 12, y: 10, text: 'Springs launch whatever touches them' },
      { type: 'spring', x: 12, y: 13 },
      { type: 'exit', x: 25, y: 2 },
    ],
    hints: [
      'The little ledge in the middle can only be reached from the spring.',
      'An echo waiting on that ledge is a springboard far above the floor.',
      'Park an echo on the ledge, then ride the spring again and bounce off it.',
      'Take 1: jump on the rubber to clear the wall, ride the spring, drift right onto the ledge and wait. Take 2: ride the spring on its second bounce, land on your echo and jump toward the tower.',
    ],
    solution: [
      'go 7; j 24; w 1; jr 40; go 12; until 125; land 14.5; go 14.5; w 8s; end',
      'go 7; j 24; w 1; jr 40; go 12; until 200; land 14.5; jr 40; r 30; go 25',
    ],
  },
  {
    id: 'w3-2',
    name: 'Burst',
    world: 3,
    objective: 'Break out of the cell and climb the tower.',
    loopSeconds: 20,
    maxEchoes: 1,
    parEchoes: 1,
    parTime: 8,
    abilities: ['burst'],
    map: [
      W,
      '#.........##.................#',
      '#.........##.................#',
      '#.........##.................#',
      '#.........##.................#',
      '#.........##..........########',
      '#.........##..........########',
      '#....P....##..........########',
      '####...#####..........########',
      '#.........##..........########',
      '#.........##..........########',
      '#.........##..........########',
      '#.....................########',
      '#.....................########',
      '#.....................########',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 5, y: 4, text: 'Shift / J: BURST — a dash in any direction, once per jump' },
      { type: 'sign', x: 5, y: 5, text: 'Cracked stone breaks under a burst or a hard landing' },
      { type: 'breakable', x: 4, y: 8, w: 3, h: 1 },
      { type: 'breakable', x: 10, y: 12, w: 2, h: 3 },
      { type: 'shard', x: 1, y: 2 },
      { type: 'exit', x: 26, y: 4 },
    ],
    hints: [
      'The cracked floor and the cracked wall will give way. The tower is too tall for a jump and a burst.',
      'A burst still works after you bounce off an echo.',
      'Leave an echo at the foot of the tower, bounce off it, then burst straight up.',
      'Take 1: jump to smash the floor, burst right through the wall and wait beside the tower. Take 2: follow, jump onto your echo, jump again as you land, then burst up and drift onto the tower.',
    ],
    solution: [
      'j 24; land; land; go 8; b r; go 20; w 8s; end',
      'go 8; until 100; go 5; land; go 17; jr 20; land 20; j 30; w 5; b u; r 40; go 26',
    ],
    lore: 'Chalk on the lab wall, in a hand I almost know: "Motion is never lost here. It only waits for someone to catch it."',
  },
  {
    id: 'w3-3',
    name: 'Battering Ram',
    world: 3,
    objective: 'Break through the heavy wall.',
    loopSeconds: 20,
    maxEchoes: 1,
    parEchoes: 1,
    parTime: 2.8,
    abilities: ['burst'],
    map: [
      W,
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#................##..........#',
      '#............................#',
      '#............................#',
      '#.P..........................#',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 5, y: 11, text: 'Side springs throw you sideways' },
      { type: 'sign', x: 12, y: 10, text: 'Heavy walls shrug off bursts — only borrowed speed breaks them' },
      { type: 'spring', x: 4, y: 14, dir: 'right' },
      { type: 'breakable', x: 17, y: 12, w: 2, h: 3, strength: 900 },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'Your own burst just bounces off the heavy wall. The side spring is not enough either.',
      'Something flying fast that hits you hands you its speed — and then some.',
      'Stand where your echo lands after the side spring, and keep rolling toward the wall.',
      'Take 1: wait a second, roll into the side spring, then brake. Take 2: wait around column 13 until your echo slams into you, and hold right.',
    ],
    solution: ['w 1s; r 34; l 40; w 8s; end', 'go 13; until 94; r 60; go 26'],
  },
  {
    id: 'w3-4',
    name: 'Catapult',
    world: 3,
    objective: 'Get upstairs, then through the heavy wall.',
    loopSeconds: 25,
    maxEchoes: 2,
    parEchoes: 2,
    parTime: 12.5,
    abilities: ['burst'],
    map: [
      W,
      '#...............##...........#',
      '#...............##...........#',
      '#...............##...........#',
      '#...............##...........#',
      '#............................#',
      '#............................#',
      '#............................#',
      '#########################.####',
      '#.......................#.####',
      '#.......................#.####',
      '#.......................#.####',
      '#.........................####',
      '#....................####.####',
      '#.P..................####.####',
      W,
      W,
    ],
    objects: [
      { type: 'sign', x: 18, y: 10, text: 'An echo that jumps beneath you throws you with it' },
      { type: 'breakable', x: 25, y: 11, w: 1, h: 1, strength: 900 },
      { type: 'breakable', x: 16, y: 5, w: 2, h: 3, strength: 900 },
      { type: 'shard', x: 27, y: 2 },
      { type: 'exit', x: 4, y: 7 },
    ],
    hints: [
      'The block in the chimney is heavy: no jump or burst of yours can crack it.',
      'Sit on an echo as it jumps and you leave far faster than any jump.',
      'One echo waits in the slot and jumps twice. The other rides the first jump upstairs and later rams you through the heavy wall.',
      'Take 1: drop into the slot, settle, tap jump at 5 s and again at 7 s. Take 2: sit on it (hold down to settle), ride the 5 s jump, wait at column 23 and burst left at 9 s. Take 3: ride the 7 s jump, stand at column 20 and hold left as you are hit.',
    ],
    solution: [
      'go 19; jr 20; go 25; sq 40; until 300; j 4; until 420; j 4; w 12s; end',
      'w 20; go 19; jr 20; go 25; sq 40; until 320; l 60; go 23; until 540; b l; w 5; r 30; w 8s; end',
      'w 40; go 19; jr 20; go 23; until 330; go 25; sq 30; until 420; l 30; go 20.5; until 544; l 3s',
    ],
    lore: 'The Archivist\'s notes: "A ball thrown upward remembers the hand that threw it. Ride it, and you remember too."',
  },
  {
    id: 'w3-5',
    name: "Newton's Cradle",
    world: 3,
    objective: 'Pass the momentum down the line.',
    loopSeconds: 25,
    maxEchoes: 3,
    parEchoes: 3,
    parTime: 10,
    abilities: ['burst'],
    map: [
      W,
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#......#.......#.......#.....#',
      '#.P....#.......#.......#.....#',
      '####.........................#',
      '#............................#',
      '#............................#',
      '########%%%%####%%%###########',
      W,
    ],
    objects: [
      { type: 'sign', x: 4, y: 9, text: 'Mud (%) swallows speed — hold Down to stop dead' },
      { type: 'breakable', x: 7, y: 12, w: 1, h: 3, strength: 900 },
      { type: 'breakable', x: 15, y: 12, w: 1, h: 3, strength: 900 },
      { type: 'breakable', x: 23, y: 12, w: 1, h: 3, strength: 900 },
      { type: 'shard', x: 10, y: 4 },
      { type: 'exit', x: 26, y: 14 },
    ],
    hints: [
      'Three heavy walls. Smashing one costs a flying ball too much speed to smash the next.',
      'A ball thrown through a wall can stop on the mud and throw the next ball.',
      'Chain it: each echo is thrown through one wall, then bursts into the next ball.',
      'Take 1: wait against the left wall, burst right at 2 s. Take 2: stand right next to it, get thrown, squash on the mud, burst right at 5 s. Take 3: stand just right of the second echo, get thrown, squash, burst right at 8 s. Take 4: stand just right of the third echo and hold right.',
    ],
    solution: [
      'go 5; go 1; until 120; b r; l 20; go 2; w 10s; end',
      'w 15; go 5; go 2; until 121; r 8; sq 40; go 10; until 300; b r; l 20; go 10; w 10s; end',
      'w 30; go 3; until 128; go 5; go 8; jr 24; go 11; until 301; r 8; sq 40; go 18; until 480; b r; l 20; go 18; w 10s; end',
      'w 45; go 3; until 135; go 5; go 8; until 305; go 8.5; jr 24; go 16; jr 24; go 19; until 482; r 3s',
    ],
    lore: 'Last page of the lab journal: "A bounce that remembers can pass from self to self forever. Perhaps that is how the Horologe was meant to keep time."',
  },
];
